feat: mvp release
- support batch command
- setup pivot_overlay

diff --git a/library/uci b/library/uci
--- a/library/uci
+++ b/library/uci
@@ -1,55 +1,70 @@
 #!/bin/sh
-# module for uci configuration.
 
-# OpenWrt-doc: http://wiki.openwrt.org/doc/techref/uci
-# ansible-doc: http://docs.ansible.com/developing_modules.html
+# OpenWrt-doc: https://openwrt.org/inbox/uci?s[]=uci
+# ansible doc: http://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html
 
-# Ansible transports arguments to modules in a file. The
-# path to the arguments file is in $1, and the file
-# contains the module's arguments like in this example:
-#
-#       name="name" value=15 dest=/tmp/destfile
-#
-# This is a little dangerous (!?!), but I'm going to ask
-# the current shell to parse that file; it will set
-# variables accordingly.
+# A non-native module accepts a filename as its only command line parameter.
+# We're going the old style way (the file contains the module args stored in
+# key=value pairs)
 
-# parameters are command, key, value
-source ${1}
+# todo: support _ansible_check_mode=True
 
-# validate arguments
-if [ -z "$command" ]; then
-        echo 'failed=True msg="Module needs command=argument"'
-        exit 0;
+_uci () {
+  uci "$@"
+  rc=$?
+  stdout_lines=$(uci changes)
+}
+
+source "${1}"
+
+if [ -z "${command}" ]; then
+  echo -n "{\"failed\": true, \"msg\": \"Module needs command=argument\"}"
+  exit 1
 fi
 
-if [ -z "$key" ]; then
-        echo 'failed=True msg="Module needs key=argument"'
-        exit 0;
+if [ "${command}" != "batch" ] && [ -z "${key}" ]; then
+  echo -n "{\"failed\": true \"msg\": \"Module needs key=argument\"}"
+  exit 1
 fi
 
-if [ -z "$value" ]; then
-        echo 'failed=True msg="Module needs value=argument"'
-        exit 0;
+if [ -z "${value}" ]; then
+  echo -n "{\"failed\": true, \"msg\": \"Module needs value=argument\"}"
+  exit 1
 fi
 
-case $command in
-    'set')
-        [ $(uci get "${key}") = "${value}" ]
-        changed=$?
-        ;;
-    'add_list')
-        uci get "$key" 2>/dev/null |grep -q "$value"
-        changed=$?
-        ;;
+case "${command}" in
+    # This is preferred and most efficient mode.
+    batch)
+      echo "${value}" | uci batch
+      # echo ${value} | sed 's/^/set /')
+      rc=$?
+      rc=0
+      stdout_lines=$(uci changes)
+      changed=$(echo "${stdout_lines}" | wc -l)
+      ;;
+    set)
+      [ $(uci get "${key}") = "${value}" ]
+      changed=$?
+      [ $changed != 0 ] && _uci "${command}" "${key}=${value}"
+      ;;
+    add_list)
+      uci get "$key" 2>/dev/null |grep -q "${value}"
+      changed=$?
+      [ $changed != 0 ] && _uci "${command}" "${key}=${value}"
+      ;;
 esac
 
-if [ $changed != 0 ]
+# if [ $changed -ne 0 ] && [ -n "$stdout_lines" ]
+[ -z "$stdout_lines" ] && changed=0
+# multiline stdout_lines breaks valid json output
+[ -n "$stdout_lines" ] && stdout_lines=$(echo $stdout_lines | xargs)
+
+if [ $changed -ne 0 ]
 then
-    uci "${command}" "${key}=${value}"
-    echo '{"changed": true, "msg": ok"}'
-    # echo "changed=True msg=executed uci ${command} ${key}=${value}"
-    exit 0
+  echo -n "{\"changed\": true, \"msg\": \"ok\", \"stdout_lines\": \"${stdout_lines}\"}"
+  uci commit
+else
+  echo -n "{\"changed\": false, \"msg\": \"ok\", \"stdout_lines\": \"${stdout_lines}\"}"
 fi
-    echo '{"changed": false, "msg": "ok"}'
-    exit 0
+
+exit $rc
